// <auto-generated />
namespace HealthMonitoring.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class make_dateofbirth_as_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_dateofbirth_as_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202010241554534_make_dateofbirth_as_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
